services:
  - type: web
    name: FINAL-EXPENSE
    env: node
    region: oregon
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    repo: https://github.com/adithya-jakka/FINAL-EXPENSE
    envVars:
      - key: JWT_SECRET
        value: your_jwt_secret_here
        sync: false
